@startuml seq-qa-uat

skinparam responseMessageBelowArrow true

mainframe Pattern: Testing

legend top left
Motivation: 
	Test 'completed' development work and ensure acceptable.

TBC: 
- qa-work is undertaken using <develop-branch> 
- qa-test is manual?
- issues relating to dropping bugs into current sprint
- uat - in-sprint with <develop-branch>?

end legend

actor ProductOwner as po
actor QAEngineer as qa
actor ScrumMaster as sm
actor Developer as dev

box QA-ENV #LightBlue
	participant GitQALocalRepo as gqlr
	participant LocalQAEnvironment as lqe
end box

box PO-TEST-ENV #LightSkyBlue
	participant GitPOLocalRepo as gplr
	participant LocalPOEnvironment as lpe
end box

box Central (Source Code and Test Environment) #LightGray
	participant GitCentralisedRepo as gc
end box

database StoryRepo as sr

autonumber 0.0
autonumber inc A

== QA - WITHIN DEV TEAM ==

autonumber 1
loop still stories untested in current sprint
	qa -> gqlr : PULL latest <develop-branch> version (contains story work to be tested)
	gqlr -> gc : PULL latest <develop-branch> version
	qa -> sr : GET QA-TEST script
	qa -> lqe: RUN QA-TEST (manual)
	
	alt pass test
		qa -> sr: mark qa testing completed and pass on for UAT
	else fail
		sm <-> qa: prioritise bug for current or future sprint
		alt current
			sm -> dev: assign for current sprint
		else future
			sm -> sr: update story repo for future reference
		end
	end

== UAT ==

loop still stories not user acceptance tested
	po -> gplr: pull latest version of <develop-branch>
	gplr -> gc: pull latest version of <develop-branch>
	po -> sr: obtain UAT script
	po -> lpe: run test
	
	alt pass test
		po -> sr: mark UAT completed and pass on for UAT
	else fail
		sm <-> po: prioritise bug for current or future sprint
		alt current
			sm -> dev: assign for current sprint
		else future
			sm -> sr: update story repo for future reference
		end
	end
end
	
end loop

@enduml
